# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deployer < Formula
  desc "the deployer cli"
  homepage "https://github.com/lukeshay/deployer"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.6/deployer_darwin_x86_64.tar.gz"
      sha256 "6e7fefec6d4dd1ac7f7e224c5561941b78ada25b44bf8a8aefad29b9e79cbe6e"

      def install
        bin.install "deployer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.6/deployer_darwin_arm64.tar.gz"
      sha256 "ab5229f0d44e4d8f41e44f93f87cdd2048f9f281f7a9486351a7fe724bff8571"

      def install
        bin.install "deployer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.6/deployer_linux_arm64.tar.gz"
      sha256 "48d71f610281e212e4ea0f4cc590863de50eb4e1841d78e1419f15397b11b9b0"

      def install
        bin.install "deployer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.6/deployer_linux_x86_64.tar.gz"
      sha256 "e9cb52acac5dcd9819dcee3a72776fa9b4b2cfb88911a253f92f682d1b90465c"

      def install
        bin.install "deployer"
      end
    end
  end
end
