# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deployer < Formula
  desc "the deployer cli"
  homepage "https://github.com/lukeshay/deployer"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.1/deployer-mac-arm64.tar.gz"
      sha256 "4a486e6a9dff0fd21041e41b28bd5bd230708729b7df39908286fad45e24a59c"

      def install
        bin.install "deployer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.1/deployer-mac-x86_64.tar.gz"
      sha256 "f37b930071e74921a185b18e7569afcfae64fbd6b0840702a8e6ec07664331cf"

      def install
        bin.install "deployer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.1/deployer-linux-arm64.tar.gz"
      sha256 "666ac7baaee0ca7dfcb0558de25e2bcc399e878e691d55cba6fa9a18e4258d48"

      def install
        bin.install "deployer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/deployer/releases/download/v0.0.1/deployer-linux-x86_64.tar.gz"
      sha256 "71fd9b57b9980f5a0ba1cff265108486942845f439da6a1604fc4c0656460cc8"

      def install
        bin.install "deployer"
      end
    end
  end
end
