# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docgen < Formula
  desc ""
  homepage ""
  version "0.0.0-1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0-1/docgen-mac-x86_64.tar.gz"
      sha256 "58e66506481a5d6185b4a0cf64579582fe5220ae7a06a5761f2165cde6e1408b"

      def install
        bin.install "docgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0-1/docgen-mac-arm64.tar.gz"
      sha256 "8d173cb204ed2397c84a4e76846c3fa60b18d94ddfb2c96212302a6d200f31d2"

      def install
        bin.install "docgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0-1/docgen-linux-x86_64.tar.gz"
      sha256 "8eea53cae632ab87ed5b6f54fd08c6575b01f68b26fe8e1dba2292b93b705e19"

      def install
        bin.install "docgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0-1/docgen-linux-arm64.tar.gz"
      sha256 "cb942f7816f607ae156716823f0e713265915452247e8ed63df4421bb870ae95"

      def install
        bin.install "docgen"
      end
    end
  end
end
