# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docgen < Formula
  desc ""
  homepage ""
  version "0.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0/docgen-mac-arm64.tar.gz"
      sha256 "ac52d3e525c68c64023d465205b3534b06f21b92d7fd5217fa384e4ca4401e3a"

      def install
        bin.install "docgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0/docgen-mac-x86_64.tar.gz"
      sha256 "e3e2a22e1115086f3cb2b378ed815b94f046b7c67388f439d9fa59640c8f87a7"

      def install
        bin.install "docgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0/docgen-linux-arm64.tar.gz"
      sha256 "1cc58b050f1ff5e189f4de508bdd4bc5a789133ed426d0eca09f8da22e2c8847"

      def install
        bin.install "docgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/docgen/releases/download/v0.0.0/docgen-linux-x86_64.tar.gz"
      sha256 "f2ee6d1ceaa05f2d87644a8ecc9adf8359af5abff294df3facf35a2c77b2c4ce"

      def install
        bin.install "docgen"
      end
    end
  end
end
