# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocden < Formula
  desc "the gocden cli"
  homepage "https://github.com/lukeshay/gocden"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukeshay/gocden/releases/download/v0.0.1/gocden-mac-arm64.tar.gz"
      sha256 "db57353e5787b97cbdd937c47976b5477185a1aa6fa1ef299250533ab1996b28"

      def install
        bin.install "gocden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/gocden/releases/download/v0.0.1/gocden-mac-x86_64.tar.gz"
      sha256 "a2c7d3bde70828e3dd82658aec3057d5067a6427f59347d4a81366240baf0a74"

      def install
        bin.install "gocden"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukeshay/gocden/releases/download/v0.0.1/gocden-linux-arm64.tar.gz"
      sha256 "36275a0fddee15f8e03de3b793a05e6bfb8f6f35915f266cc18bcb08a9707402"

      def install
        bin.install "gocden"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukeshay/gocden/releases/download/v0.0.1/gocden-linux-x86_64.tar.gz"
      sha256 "1c8a26914c7802960935d949ec50544d85e0c90888f7ddc8f9427e29de775a1d"

      def install
        bin.install "gocden"
      end
    end
  end
end
