# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pun < Formula
  desc "the pun cli"
  homepage "https://github.com/lukeshay/pun"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lukeshay/pun/releases/download/v0.0.1/pun_darwin_x86_64.tar.gz"
      sha256 "cc19a82c6c053fb730f0c01c8e5e9be34bd8fda1b1bfb074262c5bdaf204d28e"

      def install
        bin.install "pun"
      end
    end
    on_arm do
      url "https://github.com/lukeshay/pun/releases/download/v0.0.1/pun_darwin_arm64.tar.gz"
      sha256 "ce9ce9df5b6eaccbc95f80a960b697ad5c27ef19567a4a810979602742825980"

      def install
        bin.install "pun"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukeshay/pun/releases/download/v0.0.1/pun_linux_x86_64.tar.gz"
        sha256 "11a72626f3c63f0683cfb989852a22ab892832ec9ffb7ec8f055c328f06a5451"

        def install
          bin.install "pun"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lukeshay/pun/releases/download/v0.0.1/pun_linux_arm64.tar.gz"
        sha256 "52aa347a5aefc957415dfb162b20a197c5f53946cf57b3e9071494dd06a808df"

        def install
          bin.install "pun"
        end
      end
    end
  end
end
